#!/usr/bin/env bash
# =============================================================================
# Soteria Assurance — one-command Firebase client-config bootstrap
# =============================================================================
# Run this ON YOUR MACHINE (it needs your Firebase login — it cannot run in a
# sandbox without credentials):
#
#   scripts/firebase-setup.sh [--project <projectId>] [--deploy]
#
# What it does:
#   1. Verifies the Firebase CLI + login (starts `firebase login` if needed).
#   2. Finds the project's WEB app (creates one if none exists).
#   3. Fetches the public web SDK config (apiKey, appId, …).
#   4. Writes apps/web/.env.local (git-ignored) with all NEXT_PUBLIC_FIREBASE_*.
#   5. Prints the same values formatted for Vercel env vars and GitHub Actions
#      repo variables (they are PUBLIC client config, not secrets).
#   6. With --deploy: deploys Firestore rules+indexes, Storage rules, and
#      Hosting via scripts/deploy.sh.
#
# It never touches server secrets (ANTHROPIC_API_KEY / SENDGRID_API_KEY) —
# those stay in Firebase Secret Manager via `firebase functions:secrets:set`.
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/.." >/dev/null 2>&1 && pwd)"
cd "${ROOT_DIR}"

PROJECT_ID="soteria-assurance"
DO_DEPLOY="false"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --project|-p) PROJECT_ID="${2:?--project needs a value}"; shift 2 ;;
    --deploy) DO_DEPLOY="true"; shift ;;
    -h|--help)
      grep '^#' "$0" | sed -n '2,30p'; exit 0 ;;
    *) echo "[firebase-setup] Unknown argument: $1" >&2; exit 1 ;;
  esac
done

say() { echo "[firebase-setup] $*"; }

# --- 1. CLI + auth ------------------------------------------------------------
if ! command -v firebase >/dev/null 2>&1; then
  say "ERROR: Firebase CLI not found. Install it first:  npm i -g firebase-tools"
  exit 1
fi

if ! firebase projects:list --json >/dev/null 2>&1; then
  say "Not logged in — opening browser login…"
  firebase login
fi

say "Using project: ${PROJECT_ID}"

# --- 2. Find (or create) the web app ------------------------------------------
# `apps:list --json` shape: { status, result: [ { appId, displayName, platform } ] }
APP_ID="$(firebase apps:list WEB --project "${PROJECT_ID}" --json 2>/dev/null \
  | node -e 'let s="";process.stdin.on("data",d=>s+=d).on("end",()=>{try{const r=JSON.parse(s).result||[];process.stdout.write(r.length?r[0].appId:"")}catch{process.stdout.write("")}})')"

if [[ -z "${APP_ID}" ]]; then
  say "No web app registered in ${PROJECT_ID} — creating one…"
  firebase apps:create WEB "Soteria Assurance Web" --project "${PROJECT_ID}" >/dev/null
  APP_ID="$(firebase apps:list WEB --project "${PROJECT_ID}" --json \
    | node -e 'let s="";process.stdin.on("data",d=>s+=d).on("end",()=>{const r=JSON.parse(s).result||[];process.stdout.write(r.length?r[0].appId:"")})')"
fi

if [[ -z "${APP_ID}" ]]; then
  say "ERROR: could not resolve a web appId for ${PROJECT_ID}."
  exit 1
fi
say "Web app: ${APP_ID}"

# --- 3. Fetch the public SDK config -------------------------------------------
# `apps:sdkconfig --json` shape: { status, result: { sdkConfig: {...} } }
# (older CLIs put the config directly under result — handle both).
CONFIG_JSON="$(firebase apps:sdkconfig WEB "${APP_ID}" --project "${PROJECT_ID}" --json \
  | node -e 'let s="";process.stdin.on("data",d=>s+=d).on("end",()=>{const r=JSON.parse(s).result||{};process.stdout.write(JSON.stringify(r.sdkConfig||r))})')"

get() { echo "${CONFIG_JSON}" | node -e "let s='';process.stdin.on('data',d=>s+=d).on('end',()=>{const c=JSON.parse(s);process.stdout.write(c['$1']||'')})"; }

API_KEY="$(get apiKey)"
AUTH_DOMAIN="$(get authDomain)"
STORAGE_BUCKET="$(get storageBucket)"
SENDER_ID="$(get messagingSenderId)"
MEASUREMENT_ID="$(get measurementId)"

if [[ -z "${API_KEY}" || -z "${AUTH_DOMAIN}" || -z "${STORAGE_BUCKET}" ]]; then
  say "ERROR: SDK config incomplete (apiKey/authDomain/storageBucket missing)."
  say "Raw config: ${CONFIG_JSON}"
  exit 1
fi

# --- 4. Write apps/web/.env.local (git-ignored) --------------------------------
ENV_FILE="apps/web/.env.local"
cat > "${ENV_FILE}" <<EOF_ENV
# Generated by scripts/firebase-setup.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Public Firebase web SDK config for project ${PROJECT_ID} (NOT secret).
NEXT_PUBLIC_FIREBASE_API_KEY=${API_KEY}
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${AUTH_DOMAIN}
NEXT_PUBLIC_FIREBASE_PROJECT_ID=${PROJECT_ID}
NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${STORAGE_BUCKET}
NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${SENDER_ID:-830573978482}
NEXT_PUBLIC_FIREBASE_APP_ID=${APP_ID}
EOF_ENV
if [[ -n "${MEASUREMENT_ID}" ]]; then
  echo "NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=${MEASUREMENT_ID}" >> "${ENV_FILE}"
fi
say "Wrote ${ENV_FILE}"

# --- 5. Print hosting-side instructions ----------------------------------------
cat <<EOF_OUT

────────────────────────────────────────────────────────────────────────
Vercel — add these under Project → Settings → Environment Variables
(scope: Production + Preview), then REDEPLOY:

NEXT_PUBLIC_FIREBASE_API_KEY=${API_KEY}
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${AUTH_DOMAIN}
NEXT_PUBLIC_FIREBASE_PROJECT_ID=${PROJECT_ID}
NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${STORAGE_BUCKET}
NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${SENDER_ID:-830573978482}
NEXT_PUBLIC_FIREBASE_APP_ID=${APP_ID}

GitHub Actions (Firebase Hosting CI) — set the same as repo *Variables*:
  gh variable set NEXT_PUBLIC_FIREBASE_API_KEY --body "${API_KEY}"
  gh variable set NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN --body "${AUTH_DOMAIN}"
  gh variable set NEXT_PUBLIC_FIREBASE_PROJECT_ID --body "${PROJECT_ID}"
  gh variable set NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET --body "${STORAGE_BUCKET}"
  gh variable set NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID --body "${SENDER_ID:-830573978482}"
  gh variable set NEXT_PUBLIC_FIREBASE_APP_ID --body "${APP_ID}"

Console-only steps (cannot be scripted):
  • Authentication → Sign-in method: enable Email/Password, Google, Phone.
  • Authentication → Settings → Authorized domains: add your Vercel domains
    (e.g. soteria-assurance-web.vercel.app) — previews have per-PR hostnames
    and Firebase does not support wildcards; test Google/phone sign-in on a
    stable domain.
  • Functions secrets (server-only):
      firebase functions:secrets:set ANTHROPIC_API_KEY --project ${PROJECT_ID}
      firebase functions:secrets:set SENDGRID_API_KEY  --project ${PROJECT_ID}
────────────────────────────────────────────────────────────────────────
EOF_OUT

# --- 6. Optional deploy ---------------------------------------------------------
if [[ "${DO_DEPLOY}" == "true" ]]; then
  say "Deploying rules + indexes + hosting…"
  "${SCRIPT_DIR}/deploy.sh" --project "${PROJECT_ID}" --only rules
  "${SCRIPT_DIR}/deploy.sh" --project "${PROJECT_ID}" --only hosting
fi

say "Done. Local dev:  pnpm --filter @soteria/web dev"
