/**
 * Mappers from WatermelonDB model rows to Supabase rows.
 *
 * `remoteId` on a local row is the Postgres `id`. A row created offline has
 * none until its first successful push, when the database generates one and
 * the sync manager stores it back.
 */
import type { Audit as AuditDoc } from '@soteria/core';
import type { Audit } from '../db/models/Audit';
import type { ClauseAssessment } from '../db/models/ClauseAssessment';
import type { Finding } from '../db/models/Finding';
import type { Evidence } from '../db/models/Evidence';
import { nowTimestamp } from '../lib/timestamps';

// ---------------------------------------------------------------------------
// Shared helpers
// ---------------------------------------------------------------------------





// ---------------------------------------------------------------------------
// Default-row factories (used when creating a fresh local audit context).
// ---------------------------------------------------------------------------

/** A zeroed findings summary for a brand-new audit. */
export function emptyFindingsSummary(): AuditDoc['findings'] {
  return {
    totalFindings: 0,
    majorNCs: 0,
    minorNCs: 0,
    ofis: 0,
    strongPoints: 0,
    observations: 0,
    closedNCs: 0,
    openNCs: 0,
  };
}

/** A `@soteria/core` Timestamp for "now" (re-exported for convenience). */
export { nowTimestamp };

// ---------------------------------------------------------------------------
// Postgres rows
// ---------------------------------------------------------------------------

/**
 * Local models -> Supabase rows.
 *
 * Separate from the `*ToDoc` mappers above, which produced the camelCase
 * document shapes Firestore stored. Postgres columns are snake_case and the
 * id is generated by the database, so a row created offline carries no id on
 * its first push and receives one back.
 *
 * `local_created_at` / `local_updated_at` are deliberately not sent: they are
 * device clock readings, and a phone that has been offline for a day may have
 * drifted. The server's own defaults are authoritative for row timestamps.
 */

/** Fields common to every synced row. */
function baseRow(model: { tenantId: string }): Record<string, unknown> {
  return { tenant_id: model.tenantId };
}

export function auditToRow(model: Audit): Record<string, unknown> {
  return {
    ...baseRow(model),
    ...(model.remoteId ? { id: model.remoteId } : {}),
    client_id: model.clientId,
    audit_number: model.auditNumber,
    audit_type: model.auditType,
    audit_stage: model.auditStage,
    // The local schema predates the multi-standard work and stores a display
    // string; every audit captured by this build is ISO 45001.
    standard_id: 'iso45001',
    scope: model.scope,
    status: model.status,
    lead_auditor_id: model.leadAuditorId || null,
    audit_team: model.auditTeam,
    management_representative_name: model.managementRepresentativeName,
    planned_start_date: model.plannedStartDate,
    planned_end_date: model.plannedEndDate,
    audit_days: model.auditDays,
    sites_in_scope: model.sitesInScope,
    audit_plan: model.auditPlan,
    findings: model.findingsSummary,
    confidentiality: model.confidentiality,
    ai_certification_readiness_score: model.aiReadinessScore,
    ai_risk_flags: model.aiRiskFlags ?? [],
  };
}

export function clauseToRow(model: ClauseAssessment): Record<string, unknown> {
  return {
    ...baseRow(model),
    ...(model.remoteId ? { id: model.remoteId } : {}),
    audit_id: model.auditId,
    standard_id: 'iso45001',
    clause_number: model.clauseNumber,
    clause_title: model.clauseTitle,
    assigned_auditor_id: model.assignedAuditorId || null,
    conformity_status: model.conformityStatus,
    score: model.score,
    auditor_notes: model.auditorNotes,
    ai_generated_summary: model.aiGeneratedSummary,
    evidence_ids: model.evidenceIds,
    finding_ids: model.findingIds,
    sub_clause_notes: model.subClauseNotes,
    is_complete: model.isComplete,
  };
}

export function findingToRow(model: Finding): Record<string, unknown> {
  return {
    ...baseRow(model),
    ...(model.remoteId ? { id: model.remoteId } : {}),
    audit_id: model.auditId,
    client_id: model.clientId,
    finding_number: model.findingNumber,
    type: model.type,
    severity: model.severity,
    clause_number: model.clauseNumber,
    clause_title: model.clauseTitle,
    requirement: model.requirement,
    title: model.title,
    objective_evidence: model.objectiveEvidence,
    nonconformity_statement: model.nonconformityStatement,
    ai_draft_statement: model.aiDraftStatement,
    department: model.department,
    area: model.area,
    evidence_ids: model.evidenceIds,
    raised_by_auditor_id: model.raisedByAuditorId || null,
    raised_by_auditor_name: model.raisedByAuditorName,
    raised_at: model.raisedAt.toISOString(),
    target_closure_date: model.targetClosureDate || null,
    status: model.status,
  };
}

export function evidenceToRow(model: Evidence): Record<string, unknown> {
  return {
    ...baseRow(model),
    ...(model.remoteId ? { id: model.remoteId } : {}),
    audit_id: model.auditId,
    type: model.type,
    title: model.title,
    description: model.description,
    // `local_uri` never leaves the device — it points at this phone's cache.
    // The durable reference is the object path in the private bucket.
    file_url: model.fileUrl ?? '',
    file_name: model.fileName,
    file_size: model.fileSize,
    mime_type: model.mimeType,
    storage_bucket: 'evidence',
    storage_path: model.fileUrl ?? null,
    thumbnail_path: model.thumbnailUrl ?? null,
    captured_at: model.capturedAt.toISOString(),
    captured_by_auditor_id: model.capturedByAuditorId || null,
    clause_numbers: model.clauseNumbers,
    finding_ids: model.findingIds,
    is_verified: model.isVerified,
  };
}
